### ISSUE TITLE
ROCKETCHAT_USER_EMAIL_CONFIG

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [Jean-Baptiste-Lasselle/infra-kytes#6]
Un user doit pouvoir vérifier son adresse email. pour ce faire, l'instane RocketChat doit pouvoir se connecter à un serveur SMTP, et cette ocnfifguration n'est pas présente en lo'état, cf. le test suivant :+1: 

![résultat test](https://github.com/Jean-Baptiste-Lasselle/infra-kytes/raw/master/documentation/images/user-change-email-SMTP-SERVER-CONFIG1.png)

**Comment by Jean-Baptiste-Lasselle** [comment]
Extrait des logs du conteneur rocketchat : 

```bash
Exception in defer callback: Error: getaddrinfo ENOTFOUND smtp.google.com smtp.google.com:587
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

Exception in defer callback: Error: getaddrinfo ENOTFOUND smtp.google.com smtp.google.com:587
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

Exception in defer callback: Error: getaddrinfo ENOTFOUND smtp.google.com smtp.google.com:587
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

Exception in defer callback: Error: getaddrinfo ENOTFOUND smtp.google.com smtp.google.com:587
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

```
